# Generated by Django 2.2 on 2021-06-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_months', models.PositiveSmallIntegerField(choices=[(1, '1月'), (2, '2月'), (3, '3月'), (4, '4月'), (5, '5月'), (6, '6月'), (7, '7月'), (8, '8月'), (9, '9月'), (10, '10月'), (11, '11月'), (12, '12月')], verbose_name='月份')),
                ('hscode', models.CharField(max_length=20, verbose_name='HsCode')),
                ('export_data_2019', models.PositiveIntegerField(blank=True, null=True, verbose_name='2019年数据')),
                ('export_data_2020', models.PositiveIntegerField(blank=True, null=True, verbose_name='2020年数据')),
                ('export_data_2021', models.PositiveIntegerField(blank=True, null=True, verbose_name='2021年数据')),
                ('product_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='产品名')),
                ('export_type', models.PositiveSmallIntegerField(choices=[(1, 'volume of exports'), (2, 'value of exports')], verbose_name='出口类型')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
            ],
            options={
                'verbose_name': '出口数据总量',
                'verbose_name_plural': '出口数据总量',
                'db_table': 'source_data',
            },
        ),
    ]
