# Generated by Django 2.2 on 2021-06-10 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='data',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='data',
            name='export_type',
            field=models.CharField(choices=[('volume of exports', '出口量'), ('value of exports', '出口额')], max_length=128, verbose_name='出口类型'),
        ),
    ]
