# Generated by Django 2.2 on 2021-06-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20210610_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='is_delete',
            field=models.BooleanField(choices=[(True, '正常'), (False, '删除')], default=False, verbose_name='状态'),
        ),
    ]
